services:

  calculator:
    build: .
    container_name: calculator
    restart: always
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    ports:
      - 8181:8181

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - calculator
