name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag calculator:$(date +%s)

  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker run --network container:nginx appropriate/curl -s --retry 10 --retry-connrefused http://localhost/
